name: Deploy task definition to ECS

on:
  push:
    branches:
      - dev
permissions:
  id-token: write   # Required for OIDC
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: kafka-setup

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.CI_CD_ROLE_ARN }}
        
      - name: Register Task Definitions and Update Services
        run: |
          for task_file in ecs_task_definitions/*.json; do
            echo "Registering task definition: $task_file"

            # Register task definition
            TASK_DEF_ARN=$(aws ecs register-task-definition \
              --cli-input-json file://$task_file \
              --query 'taskDefinition.taskDefinitionArn' \
              --output text)

            echo "Registered: $TASK_DEF_ARN"

            # Extract family name from task def
            FAMILY=$(jq -r '.family' $task_file)

            # Assume service name = family name (can adjust if needed)
            SERVICE_NAME=$FAMILY
            CLUSTER_NAME=${{ secrets.ECS_CLUSTER_NAME_DEV }}

            echo "Updating ECS service: $SERVICE_NAME on cluster: $CLUSTER_NAME"

            aws ecs update-service \
              --cluster $CLUSTER_NAME \
              --service $SERVICE_NAME \
              --task-definition $TASK_DEF_ARN
          done